export default {
  "slug": "ai-code",
  "title": "IA et programmation",
  "description": "L'IA écrit du code, explique du code, trouve des erreurs. Comment l'utiliser pour progresser vraiment au lieu de progresser en apparence ? La méthode du développeur assisté, sans piège.",
  "story": "Assis à côté de toi, un assistant patient connaît tous les langages, propose une solution à chaque problème, explique chaque ligne trois fois sans soupirer. C'est l'IA de programmation. Réalité simultanée et paradoxale : les développeurs professionnels l'utilisent massivement, et pourtant les écoles s'inquiètent de voir des élèves produire du code qu'ils ne comprennent pas. Le paradoxe se résout simplement : l'IA est un multiplicateur de compétence. Celui qui sait programmer devient bien plus rapide ; celui qui ne sait pas devient bien plus lent le jour où l'IA se trompe, car il ne verra même pas l'erreur. Cette aventure est celle du bon usage : utiliser l'IA pour apprendre plus vite, expliquer, déboguer, suggérer, tout en gardant une règle absolue : aucun code que tu ne comprends pas n'entre dans tes projets. Prêt à devenir un développeur assisté, et non assisté-dépendant ?",
  "xp_reward": 140,
  "lessons": [
    {
      "section_type": "discover",
      "title": "L'IA développeuse : quatre usages, un danger",
      "content": "L'IA de programmation excelle dans quatre usages distincts. Un, l'explication : colle un morceau de code que tu ne comprends pas et demande : explique-moi chaque ligne comme à un débutant ; c'est un professeur disponible à toute heure. Deux, le débogage : décris ton erreur et montre ton code ; l'IA propose souvent les causes probables et les corrections : elle a vu des millions d'erreurs classiques, faute de frappe, parenthèse manquante, boucle mal bornée, confusion entre types. Trois, la suggestion : demande trois façons différentes de résoudre un problème, puis compare : voir plusieurs solutions enseigne plus qu'en voir une. Quatre, la génération : écrire du code à partir d'une description claire, ce qu'on appelle la spécification ; et c'est ici que le danger apparaît, car le code généré a trois faiblesses. Il peut être faux : l'IA compose du plausible, pas du garanti, surtout sur les cas particuliers, les cas limites, comme une liste vide, un âge négatif, une année bissextile. Il peut mentir sans le savoir : parfois il invente des fonctions de bibliothèque qui n'existent pas, phénomène bien connu appelé hallucination. Et il peut être sur-adapté : une solution élégante mais incompréhensible pour toi aujourd'hui. D'où la règle des développeurs professionnels : le code généré est une proposition, jamais une décision. On le lit ligne par ligne, on le teste avec des cas simples, on ne l'adopte que si on peut l'expliquer à voix haute à un camarade. Ce qui nous mène à la vérité la plus utile de cette leçon : plus tu demandes à l'IA d'expliquer, plus tu progresses ; plus tu lui demandes d'écrire sans expliquer, plus tu recules. La compétence reste à celui qui comprend.",
    },
    {
      "section_type": "play",
      "title": "Le juge de code : le vrai du faux",
      "content": "Jouons au juge de code, le jeu où tu apprends à ne pas croire l'IA sur parole. À deux ou en petit groupe, préparez dix extraits de code très courts, dans un langage simple que vous connaissez, ou en pseudo-code lisible par tous : trois corrects, quatre avec une erreur facile à voir, une variable mal orthographiée, une boucle qui ne s'arrête jamais, une inversion de deux lignes, une condition inversée ; et trois pièges plus subtils, un calcul juste mais mal placé, un code qui marche pour les cas simples mais échoue pour zéro. Déroulé : un joueur, l'avocat de l'IA, présente un extrait en déclarant, avec assurance : ce code est parfait, il affichera le résultat attendu. L'autre joueur, le juge, a trois minutes pour : décrire ce que le code est censé faire, dérouler son exécution à la main, ligne par ligne, avec un papier pour noter les valeurs des variables, et rendre son verdict : parfait, ou voici l'erreur, à la ligne que voici. Puis on vérifie avec l'extrait original annoté. Points : trois pour l'erreur exacte trouvée, un pour l'erreur trouvée mais mal localisée, deux pour le parfait confirmé à juste titre, et zéro pour un faux verdict. Le vrai du jeu se joue après : rejouez les trois pièges subtils avec une variante, le joueur avocat doit maintenant défendre bec et ongles un code faux, comme l'IA le fait parfois avec aplomb. Leçon finale à formuler ensemble : l'aplomb de l'énoncé ne dit rien de la vérité du code ; seule l'exécution manuelle dit vrai, et le réflexe de dérouler à la main est ce qui distingue le développeur qui comprend de celui qui copie."
    },
    {
      "section_type": "experiment",
      "title": "Expérience : la course pédagogique",
      "content": "Expérience comparative : mesure sur toi-même l'effet de deux façons d'utiliser l'IA pour apprendre un même concept de programmation, par exemple les boucles, les fonctions ou les listes, selon ton niveau. Groupe un, la méthode dépendance : avec l'accord d'un adulte, demande à l'assistant IA d'écrire un petit programme complet utilisant le concept, par exemple un programme qui affiche les nombres pairs de un à vingt, sans rien lui demander d'autre, et recopie le résultat sans le modifier. Groupe deux, la méthode tuteur : reprends le même besoin, mais avec la discipline du tuteur : demande-lui d'abord de t'expliquer le concept en dix lignes avec une analogie ; puis écris toi-même le programme sur papier, sans l'IA ; puis demande-lui de corriger ton brouillon, erreur par erreur, sans jamais te donner la solution complète, seulement des indices ; puis tape ton programme corrigé et teste-le. Vingt-quatre heures plus tard, l'épreuve de vérité, sans aucun accès à l'IA : réécris de mémoire, sur papier, un programme similaire mais différent, par exemple les multiples de trois de un à trente. Évalue les deux productions : est-ce que ça marche ? Sais-tu expliquer chaque ligne ? Serais-tu capable de le modifier si on change l'énoncé ? Rédige ta conclusion en trois phrases, en suivant la structure suivante : quand j'ai recopié, j'ai retenu ceci ; quand j'ai été guidé, j'ai retenu cela ; et donc ma règle personnelle pour l'avenir est celle-ci. La plupart des participants découvrent la même loi : la méthode tuteur demande trois fois plus d'efforts ce jour-là, et rend trois fois plus autonome le lendemain.",
    },
    {
      "section_type": "build",
      "title": "Construis ta boîte à outils de prompts dev",
      "content": "Construis ta boîte à outils de prompts de développement, dix prompts réutilisables qui font de l'IA un professeur et non un faiseur de devoirs. Prompt un, l'explicateur : explique-moi ce code ligne par ligne, comme à un débutant, avec le rôle de chaque variable. Prompt deux, le socratique : je ne comprends pas ce concept, pose-moi trois questions qui m'aident à le découvrir seul, ne me donne pas la réponse. Prompt trois, l'indexeur : mon programme a cette erreur, voici le message et mon code ; donne-moi trois indices progressifs, du plus vague au plus précis, avant la solution. Prompt quatre, le relecteur : voici mon code, il marche ; relis-le et signale les risques : cas particuliers, cas limites, lisibilité. Prompt cinq, le comparateur : montre-moi deux façons différentes de faire la même chose, avec les avantages de chacune, et laquelle convient mieux à un débutant. Prompt six, l'examineur : interroge-moi sur ce concept, cinq questions, attends ma réponse à chaque fois avant de corriger. Prompt sept, le planneur : je veux construire ce projet ; aide-moi à le découper en petites étapes que je peux coder moi-même, sans écrire le code à ma place. Prompt huit, le transformeur : voici mon code qui marche ; montre-moi comment le rendre plus lisible, sans changer ce qu'il fait. Prompt neuf, le questionneur inverse : tu es mon élève, je t'enseigne ce concept ; pose-moi les questions qu'un élève perdu poserait, pour m'aider à repérer les trous dans ma compréhension. Prompt dix, le casseur : voici mon code ; trouve trois entrées qui le feraient planter ou se comporter bizarrement. Pour chaque prompt, ajoute sur une fiche : quand l'utiliser, ce qu'il apporte, et sa limite. Mode d'emploi de la boîte : avant chaque session de code avec l'IA, choisis tes trois prompts du jour selon ton besoin du moment ; interdiction de la boîte : aucun prompt du type écris-moi mon exercice complet. Cette boîte, c'est ta charte de développeur apprenant, signée par toi."
    },
    {
      "section_type": "mission",
      "title": "Mission : l'atelier de débogage solidaire",
      "content": "Ta mission : ouvre l'atelier de débogage solidaire, un service d'aide où l'IA est ton assistant, pas ton substitut. Pendant deux semaines, propose à tes camarades de les aider à débloquer leurs programmes qui plantent, en suivant le protocole de l'atelier, rigoureux et honnête. Étape un, l'accueil : le camarade explique ce que son programme devrait faire et ce qu'il fait à la place. Étape deux, la reproduction : faites planter le programme ensemble, notant le message d'erreur exact : on ne corrige pas ce qu'on ne voit pas. Étape trois, le raisonnement partagé : avant tout recours à l'IA, vous déroulez le code à la main sur papier, en notant les valeurs, pendant cinq minutes ; très souvent, l'erreur saute aux yeux à ce stade. Étape quatre, l'IA en indices : si le mystère reste, tu consultes l'assistant IA avec ton prompt indexeur : trois indices progressifs, jamais la solution directe. Étape cinq, la réparation par le propriétaire : c'est le camarade, pas toi, qui tape la correction : on ne répare pas le code des autres, on les aide à réparer. Étape six, la vérification : testez avec le cas qui plantait, plus un cas particulier, liste vide, valeur nulle, cas extrême. Étape sept, le journal d'atelier : note chaque cas : symptôme, cause, indice qui a débloqué, temps total ; compile les erreurs les plus fréquentes du quartier des codeurs : orthographe des variables, parenthèses, boucles infinies, types confondus. Règle d'honneur de l'atelier : jamais de correction sans compréhension ; si le camarade repart sans savoir expliquer ce qui n'allait pas, la réparation a échoué, même si le programme marche. Après deux semaines, publie ton palmarès des erreurs les plus fréquentes : il vaut de l'or pour tous les codeurs débutants, et surtout pour toi.",
    },
    {
      "section_type": "project",
      "title": "Projet : le logiciel civique de ta communauté",
      "content": "Projet final : construis, avec l'IA en tuteur, un petit logiciel utile à ta communauté, et documente honnêtement le rôle de l'IA à chaque étape. Choisis un projet réaliste et mesurable : un générateur d'emploi du temps de révisions pour la classe ; un correcteur de devises pour le compte de la tontine familiale ; un quiz interactif sur l'histoire de la Côte d'Ivoire pour les plus jeunes ; un simulateur d'épargne pour un objectif scolaire ; un carnet de scores pour le tournoi du quartier. Étape un, la spécification : rédige la fiche du projet : ce que fait le logiciel, pour qui, ce qu'il ne fait pas, trois exemples d'utilisation, un par cas simple, particulier et extrême. Étape deux, le découpage avec le prompt planneur : découpe en étapes que TU peux coder ; toute étape que tu ne comprends pas se re-découpe. Étape trois, la construction disciplinée : code chaque étape toi-même ; l'IA ne sert qu'aux rôles de ta boîte à outils : expliquer, indices, relecture, casseurs ; note dans un carnet de bord chaque usage de l'IA, son type, et ce que tu as appris. Étape quatre, les tests : utilise le prompt casseur pour attaquer ton propre logiciel, corrige, puis fais tester par trois utilisateurs réels, note leurs blocages. Étape cinq, la documentation d'honnêteté : rédige la page de crédits exacte : les parties conçues et codées par toi ; les parties où l'IA t'a guidé et lesquelles ; les parties générées puis comprises et réécrites ; les sources de tes apprentissages. Étape six, la livraison : présente le logiciel à ses utilisateurs finaux avec une démonstration, ton carnet de bord en annexe : un projet dont on peut tracer exactement la part humaine et la part IA est un projet respectable. Le vrai livrable de ce projet n'est pas le logiciel : c'est la preuve, documentée, que tu sais travailler avec l'IA en restant l'auteur de ton travail.",
    }
  ],
  "quiz": [
    {
      "question": "Pourquoi dit-on que l'IA de code est un multiplicateur de compétence ?",
      "options": ["Elle rend tout le monde expert en une journée", "Elle accélère ceux qui comprennent, mais ne protège pas ceux qui ne comprennent pas des erreurs", "Elle fonctionne sans électricité", "Elle remplace les professeurs"],
      "correct_index": 1,
      "explanation": "L'IA rend le développeur compétent bien plus rapide ; mais celui qui copie sans comprendre ne voit même pas les erreurs du code généré. La compétence reste la condition du bénéfice."
    },
    {
      "question": "Qu'est-ce qu'une hallucination en programmation IA ?",
      "options": ["Un bug d'affichage sur les écrans", "Quand l'IA invente une fonction ou une bibliothèque qui n'existe pas, avec assurance", "Un rêve que fait l'ordinateur la nuit", "Une erreur de connexion internet"],
      "correct_index": 1,
      "explanation": "L'IA compose du plausible : elle peut citer avec aplomb une fonction qui n'existe pas. D'où la règle : vérifier dans la documentation officielle avant d'utiliser du code généré."
    },
    {
      "question": "Quelle est la meilleure façon d'utiliser l'IA pour progresser en programmation ?",
      "options": ["Lui faire écrire tous ses exercices pour gagner du temps", "L'utiliser comme tuteur : expliquer, donner des indices progressifs, faire deviner, puis coder soi-même", "Copier ses réponses sans les lire", "Éviter complètement l'IA pour ne pas être tenté"],
      "correct_index": 1,
      "explanation": "La méthode tuteur demande plus d'efforts sur le moment mais construit une compétence réelle et durable : explications, indices, questions socratiques. Recopier construit une illusion de compétence qui s'effondre au premier bug."
    },
    {
      "question": "Que doit-on faire du code généré par l'IA avant de l'adopter ?",
      "options": ["L'utiliser immédiatement, l'IA sait mieux que nous", "Le lire ligne par ligne, le tester sur des cas simples et particuliers, et s'assurer de pouvoir l'expliquer", "Le recopier en changeant les noms de variables", "Le rendre plus compliqué pour faire professionnel"],
      "correct_index": 1,
      "explanation": "Le code généré est une proposition : lecture, tests avec cas limites, et explication possible à voix haute sont les trois conditions d'adoption des professionnels. Un code qu'on ne peut pas expliquer n'est pas à nous."
    }
  ]
};
